name: build
on:
  pull_request:
  push:
    branches: [ 'main', 'release/**' ]

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  test-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: 1.23.x
        cache-dependency-path: |
          **/go.sum
          **/go.mod
    - name: Run tests
      run: make test
    - name: Verify
      run: make verify

  kind-linux-arm64:
    runs-on:
      group: "ARM64"
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.23.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Run tests
        run: make test
        env:
          SKIP_COSIGN_VERIFICATION: true
      - name: Verify
        run: make verify
